### ISSUE TITLE
In v6 board, U3 U7 fabrication attribute value is "Through hole"

### ISSUE THREAD

**Issue by Li-Tianming** [vroland/epdiy#108]
![1](https://user-images.githubusercontent.com/87600827/132123520-c890d38a-acfd-4805-9053-799852a0a807.png)

Is that correct? should it be changed to "surface mount"?

Thanks a lot

![2](https://user-images.githubusercontent.com/87600827/132123625-b70e0617-75bc-4a37-8e9f-369f319c2089.png)

**Comment by Li-Tianming** [comment]
![2](https://user-images.githubusercontent.com/87600827/132123625-b70e0617-75bc-4a37-8e9f-369f319c2089.png)

Same as U7, so maybe it's a mistake?

**Comment by vroland** [comment]
Yes, it should. I'll change it next time I make changes to the PCB :+1:
