### ISSUE TITLE
Looking for people to test an ePub reader

### ISSUE THREAD

**Issue by cgreening** [vroland/epdiy#116]
Hope it's ok to post this here - I've been coding up an ePUB reader and it's got to the point where it "good enough".

I've only got a LilyGO 4.7 board and was wondering if anyone could try it on their boards to see if it works...

https://github.com/atomic14/diy-esp32-epub-reader

**Comment by martinberlin** [comment]
I will give it a try!
I think you will be better off using the https://epdiy.slack.com channels since there many people that use this component hang out and share stuff.

**Comment by cgreening** [comment]
Slack button doesn't seem to work anymore - says the link is no longer valid :( - can someone invite me?

**Comment by martinberlin** [comment]
Sure Chris, just send me your email: martin@luckycloud.de

**Comment by cgreening** [comment]
Moved to slack
