### ISSUE TITLE
Invalid UTF-8 sequences cause a crash in utf8_len

### ISSUE THREAD

**Issue by cgreening** [vroland/epdiy#117]
I think the check in the for loop for seeing if you've reached the end of the UTF8 table is not quite right:

https://github.com/vroland/epdiy/blob/master/src/epd_driver/font.c line: 46

```
  for (utf_t **u = utf; *u; ++u)
```

This will run off the end as the `*u`  is not zero. It should be something like:

```
  for (utf_t **u = utf; (*u)->mask; ++u)
```

Which will run through the entries until it hits the last entry which has the structure all set to 0.

**Comment by vroland** [comment]
Good catch, thanks :)
