### ISSUE TITLE
Arduino IDE compile/upload errors caused by `boards.local.txt`

### ISSUE THREAD

**Issue by Sam-Izdat** [vroland/epdiy#133]
Arduino IDE 1.8.18
Board: LILYGO-T5 4.7 inch
OS: Windows 10

Followed the documentation to set up epdiy as Arduino IDE library (side note: apparently boards.txt directory is now in `C:\Users\[User]\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.1` which took a while to locate). Copied boards.local.txt. The boards list populated, but compiling any sketch raised the error:

    exec: "--elf-gcc.path}/bin/--elf-g++": file does not exist
    Error compiling for board LILYGO T5-4.7 inch e-paper.

Adding the following missing lines to boards.local.txt before `[board].build.mcu` line resolved the compilation error:

    lilygo_t5_47.build.tarch=xtensa
    lilygo_t5_47.build.bootloader_addr=0x1000
    lilygo_t5_47.build.target=esp32

An upload error followed, complaining about upload flags. Adding the following missing lines to boards.local.txt after `[board].upload.wait_for_upload_port` line resolved the upload error:

    lilygo_t5_47.upload.flags=
    lilygo_t5_47.upload.extra_flags=

I assume these errors need to be resolved for every board, but I have not tested this.

**Comment by vroland** [comment]
Good to know! It might also have something todo with the new 2.0.0 version of the arduino esp32 core. Would you mind submitting a pull request with the required changes?

**Comment by Sam-Izdat** [comment]
Not at all! I'll try and get it in this weekend. I'm unable to to test the other boards fully, so will have to just assume the uploaf fix is universal unless someone can check and finds otherwise.

**Comment by Sam-Izdat** [comment]
Put in pull request #135 - using master branch. I can resubmit if you need this on another branch instead.

**Comment by vroland** [comment]
Thanks, merged :)
