### ISSUE TITLE
Status der PCB

### ISSUE THREAD

**Issue by holgerlembke** [vroland/epdiy#14]
Danke für das großartige Projekt!

Ich plane ein paar epdiy-PCBs machen zu lassen und dann rumzubasteln. 

Wie ist der Status der PCBs unter https://github.com/vroland/epdiy/tree/master/hardware/epaper-breakout/gerbers? Nicht das ich bestelle und drei Tage später eine dolle Änderung gemacht wird...

**Comment by vroland** [comment]
Wahrscheinlich sind die nicht mehr ganz aktuell, also vielleicht lieber noch einmal exportieren ;)
Ansonsten enthält die Gerbers_v2_rev0.zip die von mir zuletzt erfolgreich Bestellten, allerdings ohne die ab dort eingearbeiteten Verbesserungen.

**Comment by holgerlembke** [comment]
Ja, ein aktueller Export wäre eine schicke Sache.

**Comment by vroland** [comment]
Was meinst du mit 09446309680041?

**Comment by holgerlembke** [comment]
Gemeint habe ich ED097OC4. Bin zu blöd, die Zwischenablage zu bedienen.

Danke für das Update.

**Comment by vroland** [comment]
Falls du das Display meinst: Ebay / Aliexpress. Der Konnektor sollte bei den üblichen Distributoren zu finden sein.

**Comment by holgerlembke** [comment]
Danke für die Hinweise. 

Ich bin mit den Einzelteilen halbwegs durch, es hat keine große Eile...
