### ISSUE TITLE
Why framebuffer is half of `EPD_WIDTH * EPD_HEIGHT`?

### ISSUE THREAD

**Issue by lanistor** [vroland/epdiy#141]
Does this means the actual rendered resolution is half the screen resolution?

**Comment by vroland** [comment]
That is because for 16 grayscale values, we only need 4 bits, so 2 pixels per byte. No need to waste space by using a 8 bit-per-pixel buffer ;)

**Comment by martinberlin** [comment]
Hi @lanistor, 
If you understood it and this is not any more an open issue, please close it. Thanks!

**Comment by lanistor** [comment]
OK, thanks for helping to close it.
