### ISSUE TITLE
Slack invitation link in badge has expired

### ISSUE THREAD

**Issue by sychan** [vroland/epdiy#142]
I went to try the Slack workspace, but the link has expired. Is the Slack workspace still going? Maybe update or remove the slack badge?

**Comment by martinberlin** [comment]
Hello Steve, I just sent you an email invitation to Slack with the address you have in the GitHub profile.

**Comment by mickeprag** [comment]
I would like to join as well. Better perhaps to fix the invite badge?

**Comment by martinberlin** [comment]
If you want Micke I can send you an invitation to an email address. Only @vroland I suppose has the rights to fix the Readme page and to get a new link from Slack.

**Comment by mickeprag** [comment]
Yes, please send me a link as well. Thank you.

**Comment by martinberlin** [comment]
> Yes, please send me a link as well. Thank you.

Sorry to what email ? (There is none in your GitHub profile)

**Comment by mickeprag** [comment]
micke.prag@gmail.com

**Comment by vroland** [comment]
Unfortunately, the invite link expires every 30 days and slack does not allow to extend this period :/ So thanks for the reminder, I updated the link :)
