### ISSUE TITLE
Potential issue with GPIO12

### ISSUE THREAD

**Issue by sebastius** [vroland/epdiy#17]
GPIO12 (MTDI pin) on the ESP32 when pulled high on boot sets another LDO voltage: 

<img width="588" alt="image" src="https://user-images.githubusercontent.com/14947839/86185402-9d4e3d80-bb36-11ea-89a8-954ba02a5a24.png">

Which will cause a brownout on the flash-chip in the wrover. We've learned that the hard way with the Hackerhotel 2019 badge project i was part of. 

No idea if the display is capable of pulling the pin high on boot, but it might be interesting to verify. I have a few V2 boards (with my modifications bodged in)  that aren't booting right now, will look into this. 

A fix is relatively easy: burning a fusebit will set the voltage permanently. It is however unfortunate that not all wrovers require the same voltage IIRC.

**Comment by vroland** [comment]
The more you know... Thanks for sharing! So far I did not encounter the issue with any of my displays, but when I've got access to as scope I can look for anything suspicious.

**Comment by vroland** [comment]
If I'm seeing it corrently, GPIO12 is not connected to any display pin. It is broken out as MISO, thus the internal pull-down should do its job...

**Comment by sebastius** [comment]
I think i misread the schematic then :) So it's a non-issue, might be useful to update the readme with a caveat.

**Comment by vroland** [comment]
Addressed in f4ac37aca000ada40e4d3596885bfed7beea1846.
