### ISSUE TITLE
Updated KiCad files

### ISSUE THREAD

**Issue by mzabrams** [vroland/epdiy#18]
Would it be possible to get the .pcb and .sch files that correspond to the latest gerbers updated in the repo?

**Comment by vroland** [comment]
The KiCad files in the repo are always the most current version, the gerbers are exported from those.

**Comment by mzabrams** [comment]
It looks like the KiCad files were last updated 28 days ago, but the gerbers were updated 6 days ago -- I may be misreading something or not following the commit notes, so apologies if I'm mistaken on that.

**Comment by vroland** [comment]
I just forgot to update the exported files, which #14 reminded me of 6 days ago.

**Comment by mzabrams** [comment]
Gotcha, thanks for clarifying that!
