### ISSUE TITLE
Source file comment issue in rmt_pulse.c

### ISSUE THREAD

**Issue by Li-Tianming** [vroland/epdiy#189]
The comment said `// currently hardcoded: use channel 0 `

https://github.com/vroland/epdiy/blob/4ad561586916093a4b8bd0a7ee94485a3ac23cd9/src/epd_driver/rmt_pulse.c#L24

but actually it use `CHANNEL_1`

https://github.com/vroland/epdiy/blob/4ad561586916093a4b8bd0a7ee94485a3ac23cd9/src/epd_driver/rmt_pulse.c#L25

i tried other channle like`CHANNEL_4` , it workes.

so maybe it's just a misspelling?

**Comment by martinberlin** [comment]
Hi Li,
Please provide clear information on how to reproduce this.
What board you are using?
With what frnmework? (Arduino-esp32/esp-idf)

**Comment by Li-Tianming** [comment]
I use V5 board and esp-idf V4.4

I think comment in this line 

https://github.com/vroland/epdiy/blob/4ad561586916093a4b8bd0a7ee94485a3ac23cd9/src/epd_driver/rmt_pulse.c#L24

is wrong

it should be 

` // currently hardcoded: use channel 1`
