### ISSUE TITLE
possible null pointer reference and error in order of execution....

### ISSUE THREAD

**Issue by holgerlembke** [vroland/epdiy#19]
I was reading stuff to fall asleep last night....

https://github.com/vroland/epdiy/blob/8b19eb32aa55d6df0f06a928782b1d16c77d238e/components/epd_driver/font.c#L284

should be 
```
uint8_t bg = props.bg_color;
```
because the null pointer check some lines up.

https://github.com/vroland/epdiy/blob/8b19eb32aa55d6df0f06a928782b1d16c77d238e/components/epd_driver/font.c#L318

Why first assign something and then check for null? Should be swapped.

**Comment by vroland** [comment]
Ah, good catch, thank you :)
