### ISSUE TITLE
V6 lacking R2 & R5 values

### ISSUE THREAD

**Issue by Alfamos** [vroland/epdiy#193]
Trying to clone this project and implementing it, I have encountered an issue. There is no value for the R5 resistor and the R2 one is indicating a 200 value, and does not correspond with the BOM file which is 400.

I am a newbie in the PCB building community, so maybe I am doing something wrong. Please let me know.

**Comment by martinberlin** [comment]
Hi Alfamos,
I really don't find any issue with this (And no problem with being a newbie here, I'm also one)

**R2** in schematic is correctly labeled as 400 which means 400 Ohm. Although [LCSC part is a 390Ω](https://jlcpcb.com/parts/componentSearch?isSearch=true&searchTxt=C23151) that is probably the closest value.
**R5** is marked [in the BOM](https://github.com/vroland/epdiy/blob/master/hardware/epaper-breakout/BOM.csv) as a 0 Ohm resistance and also properly labeled in the Schematic.

This PCB was sent to fabrication by different people and it's proved to be working.
