### ISSUE TITLE
How to refresh full screen without clean the buffer?

### ISSUE THREAD

**Issue by lanistor** [vroland/epdiy#206]
How to refresh full screen without clean the buffer?
`epd_clear` seems will clean the buffer data, then no way to render again.

I can only found the follow way, this will need malloc another buffer temply:
```c++
void epdiy_fullclear() {
  int fb_size = epd_rotated_display_width() * epd_rotated_display_height() / 2;
  uint8_t* buffer = epd_hl_get_framebuffer(&hl);

  void* copy_buffer = heap_caps_malloc(fb_size, MALLOC_CAP_SPIRAM);
  memcpy(copy_buffer, buffer, fb_size);

  epd_fullclear(&hl, temperature);

  memcpy(buffer, copy_buffer, fb_size);
  heap_caps_free(copy_buffer);

  epd_hl_update_screen(&hl, updateMode, temperature);
}
```

**Comment by vroland** [comment]
Hm, I suppose the highlevel API currently does not allow this, as it looks for parts that have changes first. Maybe an additional function like `epd_hl_redraw` would be nice that just re-daws everything. I suppose that would also help with #205 ...

**Comment by lanistor** [comment]
Thanks for reply.

**Comment by martinberlin** [comment]
Hello @lanistor 
What is the status of this?
You made #217 pull-request but later was closed. Shall we add this to #205 as **vroland** suggested?

**Comment by lanistor** [comment]
I will create a new PR after tested v7, now i close this issues.
