### ISSUE TITLE
Will epd_poweroff save power?

### ISSUE THREAD

**Issue by lanistor** [vroland/epdiy#208]
In our test, the current basically does not change after call `epd_poweroff`.

**Comment by martinberlin** [comment]
Please specify how is your test adding a correct explanation on how to reproduce it.
**epd_poweroff** should turn off the high voltage so if you don't see a change in consumption after that then you are clearly doing somthing wrong. But adding an issue with just one line explaining what happens will not help you to find a solution.

**Comment by lanistor** [comment]
Thanks, this helps a lot.
