### ISSUE TITLE
Community channel & communcation

### ISSUE THREAD

**Issue by olup** [vroland/epdiy#209]
Hi, 

This is not a tech issue. 
Two community exchange are stated - matrix and slack - however the slack invite is not working anymore.
The question:
- Is any of the two platform preferable for asking questions ?
- Can the slack be shared again ?

Cheers !

**Comment by martinberlin** [comment]
Hi Olup, welcome!
I'm only in Slack. The problem is that the link is valid just for a month and then expires.'
Please send me your email to the one you can see in my profile and I will send you an invitation.

**Comment by olup** [comment]
Done - and thanks
