### ISSUE TITLE
Made a version of Weather example for Arduino:

### ISSUE THREAD

**Issue by gfaman** [vroland/epdiy#216]
Hi,

I adapted and made some small corrections in the example weather for Arduino.
Working fine for V5 PCBA and 9.7'' display
https://github.com/gfaman/Weather-example-E-paper-Arduino

Laurent

**Comment by skorokithakis** [comment]
There's nothing in that repo.

**Comment by martinberlin** [comment]
Sorry but I'm closing this as mentioned before the repository is empty and also this Issues board primary goal is to detect bugs or propose enhancements.

**Comment by gfaman** [comment]
Sorry, made a mistake when create the repository and was empty
Uploaded again the files and new seems ok.

**Comment by DongBH** [comment]
well done.
