### ISSUE TITLE
V6 can't work

### ISSUE THREAD

**Issue by 3058132083** [vroland/epdiy#223]
ESP_ERROR_CHECK failed: esp_err_t 0xffffffff (ESP_FAIL) at 0x400deb8c
0x400deb8c: epd_board_poweron at C:/msys64/home/Administrator/epdiy/src/epd_driver/board/epd_board_v6.c:208 (discriminator 1)

file: "C:/msys64/home/Administrator/epdiy/src/epd_driver/board/epd_board_v6.c" line 208
func: epd_board_poweron
expression: tps_write_register(config_reg.port, TPS_REG_ENABLE, 0x3F)

abort() was called at PC 0x4008fdf4 on core 0
0x4008fdf4: _esp_error_check_failed at C:/Espressif/frameworks/esp-idf-v5.0.1/components/esp_system/esp_err.c:47

Backtrace: 0x40082519:0x3ffbad90 0x4008fdfd:0x3ffbadb0 0x400967b5:0x3ffbadd0 0x4008fdf4:0x3ffbae40 0x400deb8c:0x3ffbae70 0x400dd471:0x3ffbaea0 0x400dbf8f:0x3ffbaec0 0x400dc56f:0x3ffbb0c0 0x40163029:0x3ffbb0e0
0x40082519: panic_abort at C:/Espressif/frameworks/esp-idf-v5.0.1/components/esp_system/panic.c:423

0x4008fdfd: esp_system_abort at C:/Espressif/frameworks/esp-idf-v5.0.1/components/esp_system/esp_system.c:153

0x400967b5: abort at C:/Espressif/frameworks/esp-idf-v5.0.1/components/newlib/abort.c:38

0x4008fdf4: _esp_error_check_failed at C:/Espressif/frameworks/esp-idf-v5.0.1/components/esp_system/esp_err.c:47

0x400deb8c: epd_board_poweron at C:/msys64/home/Administrator/epdiy/src/epd_driver/board/epd_board_v6.c:208 (discriminator 1)

0x400dd471: epd_poweron at C:/msys64/home/Administrator/epdiy/src/epd_driver/display_ops.c:40

0x400dbf8f: epd_task at C:/msys64/home/Administrator/epdiy/examples/mpd_status/main/main.c:165

0x400dc56f: app_main at C:/msys64/home/Administrator/epdiy/examples/mpd_status/main/main.c:360

0x40163029: main_task at C:/Espressif/frameworks/esp-idf-v5.0.1/components/freertos/FreeRTOS-Kernel/portable/port_common.c:131 (discriminator 2)

ELF file SHA256: 4b2da0f391ada863

Rebooting...

**Comment by 3058132083** [comment]
Do you have a discord channel to discuss these issues

**Comment by vroland** [comment]
We don't have discord, but there is a slack channel ;)
Apparently the TPS chip does not respond to I2C. Usually this is a soldering issue. Can you double-check the soldering? Also, does the TPS chip show up in an I2C scan?

**Comment by 3058132083** [comment]
OK,I'll check it.

**Comment by 3058132083** [comment]
I rewelded, and now there is no error message, but there is still no voltage

**Comment by martinberlin** [comment]
> I rewelded, and now there is no error message, but there is still no voltage

Check the return error messages that come from TPS65185 from I2C. If PWR_GOOD signal does not turn HIGH there is some issue with starting the voltage pumps. Check datasheet, I use to have to have some similar issues and I remember it helped to read the values.

https://www.ti.com/product/TPS65185#tech-docs

**Read datasheet with detail:**

- Feature Description (continued)  8.3.8 Fault Handling And Recovery
- Table 8. INT_EN1 Register Field Descriptions 
- Table 9. INT_EN2 Register Field Descriptions

Understanding the values of those two registers can be the key to understand what is going on. 
Check also that the power to TPS PMIC is stable.

**Comment by martinberlin** [comment]
@vroland I think that it will be nice in this topic, for example for the developers starting with V6, to have a Firmware demo that just starts TPS65185 and makes some checks. Also delivers the INT_EN1, INT_EN2 values maybe with some additional info coming from the hardware that we can define. So it's easier to find where the error is.
Because I know how frustrating can be to debug it when you don't get the high voltages running...

**Comment by mickeprag** [comment]
This patch at least prints the INT1/2 registers to the log:
https://github.com/vroland/epdiy/pull/248/commits/13fd04ef93b47559c3799bdd5170e538d4fb579b

**Comment by martinberlin** [comment]
Thanks Micke,
@3058132083 there is more than 2 months without any feedback from your side. Closing this unless you really want to keep on trying.
Please contact me at the email that you can see in my github profile and I will reopen this then.
