### ISSUE TITLE
Update Slack invite link

### ISSUE THREAD

**Issue by alexose** [vroland/epdiy#224]
The current invite link seems to have expired:

<img width="454" alt="image" src="https://user-images.githubusercontent.com/627264/224564302-917b4a02-0ba4-4172-9282-1025a39fee50.png">

**Comment by martinberlin** [comment]
Please send me your email to the one you can find in my GitHub profile. Free slack invitation links expire in one month so it does not make much sense to update it all the time

**Comment by martinberlin** [comment]
Link was sent using email

**Comment by martinberlin** [comment]
If anyone needs an Slack invite please send me a short email to Martin at Cale.es
