### ISSUE TITLE
Question about Parts List / BOM

### ISSUE THREAD

**Issue by SimonSelg** [vroland/epdiy#23]
Hi @vroland,

thanks for the cool project! Looks very nice :) I would like to build a board too! 

I was wondering which parts list to use:
- [hardware/BOM.csv](../tree/master/hardware/BOM.csv) or
- [hardware/epaper-breakout/partlist.ods](../tree/master/hardware/epaper-breakout/partlist.ods)

I see that in the newest version of the PCB a jumper was added, I guess that one could be added into the parts list too. Or did I get this wrong?

Or should I refer to the schematics and get the required parts from there? 

Thanks a lot!

**Comment by vroland** [comment]
Hi,

they should refer to the same parts, but the CSV does not contain specific part numbers. But it won't hurt to double check :)
The jumper is a solder jumper, which you have to solder / scratch, so there is no part for that ;)

Regards, 
Valentin

**Comment by SimonSelg** [comment]
Hi, thanks for quick reply. That answers the question, I'll start compiling a  list of parts I need now.

Have a great weekend!
