### ISSUE TITLE
Will epdiy support Power-Management of ESP?

### ISSUE THREAD

**Issue by lanistor** [vroland/epdiy#255]
When open [Power Management](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/power_management.html), then painting will have weird behavior (paint on wrong area, blurry image), even set CPU frequency to 240MHz (use `ESP_PM_CPU_FREQ_MAX` lock mode).

**Comment by martinberlin** [comment]
I don't think implementing of PM has to be done in this library but rather on the Firmware that implements this library.
Basically epdiy already takes care of consuming the minimum possible letting the user do an epd_poweroff() right after refreshing the display switching all high voltages off.

> When open [Power Management](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/power_management.html), then painting will have weird behavior (paint on wrong area, blurry image), even set CPU frequency to 240MHz

Reading the documentation says:  **Enabling power management features comes at the cost of increased interrupt latency. Extra latency depends on a number of factors, such as the CPU frequency, single/dual core mode, whether or not frequency switch needs to be done.**

This sounds to me like they are adding locks in some parts which will add latency. And that will not play well with this component.

Power Management if used should be at the highest CPU level when epdiy is transmitting when possible and then when it's not communicating with the display can be set to lower values. If you already tried this and does not work as expected is because either is not correctly setup or the settings are adding latency in the parallel communication affecting how the data arrives to the display.

Now if this would be considered at any point is not for me to decide but rather **vroland** that is the project owner.

**Comment by lanistor** [comment]
> Power Management if used should be at the highest CPU level when epdiy is transmitting when possible and then when it's not communicating with the display can be set to lower values. If you already tried this and does not work as expected is because either is not correctly setup or the settings are adding latency in the parallel communication affecting how the data arrives to the display.

Yeah, i did as this, the CPU frequency is 240MHz, and the APB frequency is 80MHz, both same as disabled `Power Management`, but the painting still have error.

Just open `PM` by check `Component config` - `Power Management` - `Support for power management`, don't check `Enable dynamic frequency scaling (DFS) at startup`, and don't add any PM code in `demo` of `epdiy`, this condition, `PM` will not run, and all frequency (CPU, APB) will be same as before (by `esp_clk_cpu_freq`, `esp_clk_apb_freq`), but the painting will like this:
![](https://github.com/lanistor/assets/blob/master/epaper/pm/img-1.jpg?raw=true)
Besides, the painting speed will be slower, and painting intervals will become longer.

I wan't to close `PM` before painting, and open `PM` after painting, but this behavior seems `epdiy` rely on some code affected by `PM` macro definition (`CONFIG_PM_ENABLE`), but i cannot find it out, so i don't know how to change the code.

Here is the videos i recorded by v6 board: [Video1](https://github.com/lanistor/assets/blob/master/epaper/pm/video-1.mp4), [Video2](https://github.com/lanistor/assets/blob/master/epaper/pm/video-2.mp4), [Video3](https://github.com/lanistor/assets/blob/master/epaper/pm/video-3.mp4), v5 has the same behavior.

**Comment by vroland** [comment]
Hm, it seems plausible that the power management interferes with interrupt timing and possibly RMT clocks. It may be a small fix, but it also may take a lot of fiddling with the timing. 
Since for many people, "Power Management" will be just going to deep sleep, I'd rather focus on getting the V7 firmware done for now. There is probably a way to make it work together, I just can't estimate the development time needed...

**Comment by lanistor** [comment]
Agree to deal with v7 first, this is a great project.

I think `Power Management` is not only for sleeping, if just for sleeping, we can use [normal sleep mode](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/sleep_modes.html) , but this will stop WiFi connection, and reconnect again when wake up, this may take more than 10 seconds and give users a poor experience.

`PM` can fall to sleep with maintaining WiFi connection, i think it's a good solution for scenes those need both network and low power consumption.

I'm connecting with developers at Espressif company for this, i will share any messages once i got some.

**Comment by martinberlin** [comment]
> PM can fall to sleep with maintaining WiFi connection, i think it's a good solution for scenes those need both network and low power consumption.

This will be something new for me. It would be rather difficult that the micro-controller sleeps while maintaining any kind of Radio connectivity. It's precisely WiFi what has more consumption than anything else in this MCUs.
In the document says:

> WiFi: between calls to [esp_wifi_start()](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/network/esp_wifi.html#_CPPv414esp_wifi_startv) and [esp_wifi_stop()](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/network/esp_wifi.html#_CPPv413esp_wifi_stopv). If modem sleep is enabled, the lock will be released for the periods of time when radio is disabled.

But in any moments mentions that sleeps while WiFi is connected. It might sleep just when Radio is off adding this locks that mentions automatically.

**Comment by lanistor** [comment]
I found this in the [document](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/sleep_modes.html#_CPPv421esp_light_sleep_startv):
> If Wi-Fi/Bluetooth connections need to be maintained, enable Wi-Fi/Bluetooth Modem-sleep mode and automatic Light-sleep feature (see [Power Management APIs](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/power_management.html)). This allows the system to wake up from sleep automatically when required by the Wi-Fi/Bluetooth driver, thereby maintaining the connection.

**Comment by vroland** [comment]
Also, making this compatible with light-sleep or active wifi connection and clock down would make the component more robust and eliminate a source of errors for users. It's likely that the actual required changeset would be quite small, but the associated research maybe not.

**Comment by lanistor** [comment]
@vroland As a tested, the v7 board can work with Power Management by `PM-Lock` perfectly, the painting will be normal by the below code:
```cpp
#if CONFIG_PM_ENABLE
#if CONFIG_IDF_TARGET_ESP32
  esp_pm_config_esp32_t pm_config = {
#elif CONFIG_IDF_TARGET_ESP32S2
  esp_pm_config_esp32s2_t pm_config = {
#elif CONFIG_IDF_TARGET_ESP32C3
  esp_pm_config_esp32c3_t pm_config = {
#elif CONFIG_IDF_TARGET_ESP32S3
  esp_pm_config_esp32s3_t pm_config = {
#endif
    .max_freq_mhz = CONFIG_ESP32_DEFAULT_CPU_FREQ_MHZ,
    .min_freq_mhz = 80,
#if CONFIG_FREERTOS_USE_TICKLESS_IDLE
    .light_sleep_enable = false
#endif
  };
  ESP_ERROR_CHECK(esp_pm_configure(&pm_config));
#endif // CONFIG_PM_ENABLE


// Below for updating screen

static esp_pm_lock_handle_t rmt_send_task_pm_lock;

#if CONFIG_PM_ENABLE
  // Add PM-Lock before painting
  static esp_pm_lock_handle_t rmt_send_task_pm_lock;
  ESP_ERROR_CHECK(esp_pm_lock_create(ESP_PM_CPU_FREQ_MAX, 0, "rmt_send_task",
                                     &rmt_send_task_pm_lock));
  ESP_ERROR_CHECK(esp_pm_lock_acquire(rmt_send_task_pm_lock));

  epd_poweron();
  epd_hl_update_area(&hl, updateMode, temperature, update_area);
  epd_poweroff();

  // release PM-Lock after painting
  ESP_ERROR_CHECK(esp_pm_lock_release(rmt_send_task_pm_lock));
#endif // CONFIG_PM_ENABLE
```

But the v5, v6 board will painting with error like this: 
![](https://github.com/lanistor/assets/blob/master/epaper/pm/img-1.jpg?raw=true)
The PM-Lock has not effect on the board.
And i contacted with developers at Espressif company, they had tested for MCU and said there is no problems on ESP32.

So what will be the problem? I have no idea.

**Comment by lanistor** [comment]
Finally i found a way to resolve this problem on v5, v6 board: Set the frequency to `160MHz` instead of `240MHz`.

I don't know why this can make the `PM-Lock` work, v7 board doesn't need to do this.

And another problem: will this change slow down the speed of painting?

**Comment by lanistor** [comment]
Unfortunately, i tested LCD screen with a developement board of ESP32-WROVER-B, it can run perfectly with `PM` and `PM-Lock`, and in all CPU frequency, so it's hard to communicate with developers at Espressif company for this problem.

**Comment by martinberlin** [comment]
The drawing speed difference will be minimal and almost no noticiable. Also running at a lower CPU speed the consumption will be lower.
Good work finding a solution for the v5 board!

**Comment by lanistor** [comment]
Got it, thanks.
