### ISSUE TITLE
GUI Software

### ISSUE THREAD

**Issue by mataide** [vroland/epdiy#257]
Hello guys,

Are we able to use GUI software like Squareline Studio (or other software) to create the layout and use this driver together?

Thanks,

**Comment by martinberlin** [comment]
Hello Mataide,
Epdiy mission is to be the controller board plus firmware, along with some examples to get started.
All the rest has to be build using this part to drive the display.

If you check my repositories you can find https://github.com/martinberlin/lv_port_esp32-epaper that is my take to make a LVGL driver for epdiy. What is not so easy is to get a touch that works except from the 6” that are popular in ereaders, all the rest comes without touch. To try this LVGL I’ve used a small Lilygo EPD47 and for the 9” I found a GPS touch called GT911.
