### ISSUE TITLE
Out-of-date documents

### ISSUE THREAD

**Issue by 3058132083** [vroland/epdiy#282]
I can't find the settings for boards version and VCOM in menuconfig
![image](https://github.com/vroland/epdiy/assets/52588960/10e857d9-3c63-4c5c-b8a9-d50a0fbcfe1d)

**Comment by martinberlin** [comment]
On latest version this won’t appear at all in menuconfig.
It is instead initialized by code. Just check the examples in **main** branch

**Comment by 3058132083** [comment]
I see
