### ISSUE TITLE
Check Compatibility with ESP-IDF 4.1/4.2

### ISSUE THREAD

**Issue by vroland** [vroland/epdiy#29]
see #28 .

**Comment by aldwinhermanudin** [comment]
I've checked on this. It doesn't work for me when using ESP-IDF 4.1

**Comment by vroland** [comment]
@aldwinhermanudin Ok, thanks. Then I'll have to look into it at some point.

**Comment by mcer12** [comment]
@aldwinhermanudin  For me 4.1 (currently default on windows) didn't work, 4.2 branch works.

**Comment by iromeo** [comment]
With ESP-IDF v4.2 + master branch (or revision_3 branch) works ok. With  v4.1 also doesn't work for me, get kernel panic errors on display init.

**Comment by vroland** [comment]
There seems to be a driver bug (or change) with the RMT peripheral driver in 4.1. But since it works with 4.2+, a note in the readme might do?

**Comment by 2dom** [comment]
Add 

 ` rmt_driver_install(row_rmt_config.channel, 0,0);
`
before

`  rmt_set_tx_intr_en(row_rmt_config.channel, true);`

rmt_pulse.c

**Comment by vroland** [comment]
Ok, I'll try that, thanks :)

**Comment by vroland** [comment]
Unfortunately, when using the RMT driver I can't use interrupts in the way I need to because it installs its own ISR. Since this is fixed in IDF 4.2 which is officially released now, I just added a compile-time error for IDF 4.1.
