### ISSUE TITLE
Slack link is dead

### ISSUE THREAD

**Issue by amadeok** [vroland/epdiy#295]
Hi,
the slack link in the description doesn't work, is there still a slack or something similar?
thanks

**Comment by martinberlin** [comment]
Hola Amadeo,
Here you have it https://join.slack.com/t/epdiy/shared_invite/zt-2g3dpt45i-V5vleYuxcwoM9Rbz2tXtRA
We are trying to move out of slack though I will recommend you to try discussions here https://github.com/vroland/epdiy/discussions
