### ISSUE TITLE
Will epd_push_pixels_lcd in s3 support partial area?

### ISSUE THREAD

**Issue by lanistor** [vroland/epdiy#320]
`epd_push_pixels` will always paint full screen on s3 board, for the macro `RENDER_METHOD_LCD`.
What should i to do for partial area clear?

**Comment by vroland** [comment]
Ah indeed. Probably it would need pre-population of a masked line buffer for the affected lines, and then orchestrate the callbacks appropriately.

**Comment by lanistor** [comment]
> Ah indeed. Probably it would need pre-population of a masked line buffer for the affected lines, and then orchestrate the callbacks appropriately.

It this need to modify the hardware circuit board? or only modify the software code?

**Comment by vroland** [comment]
Only software modifications. Shouldn't be too crazy.

**Comment by lanistor** [comment]
Waiting for your update👍.

> Only software modifications. Shouldn't be too crazy.

**Comment by lanistor** [comment]
@vroland Is this problem in plan?

**Comment by lanistor** [comment]
@vroland Is there any i can do to support it? May you guide me to do it?

**Comment by vroland** [comment]
Hey, can you test if #364 fixes it for you? I finally found some time to just do it, it's not a lot of work at the end of the day.

**Comment by lanistor** [comment]
> @lanistor hey, can you test if #364 fixes it for you? I finally found some time to just do it, it's not a lot of work at the end of the day.

OK, i will test it soon, thanks a lot👍👍👍

**Comment by lanistor** [comment]
@vroland I has tested it (https://github.com/vroland/epdiy/pull/364), it can works perfect! Thanks a lot. 👍👍👍
