### ISSUE TITLE
The Readme states ED060SC4 is compatible but it isn't

### ISSUE THREAD

**Issue by floers** [vroland/epdiy#355]
The [Displays](https://github.com/vroland/epdiy?tab=readme-ov-file#displays) section states that ED060SC4 is compatible since version 2. My understanding was that this would mean it is working with the latest version of epdiy but v7 has no 39 pin port so it can't be compatible and the only adapter documented is specifically not compatible for ED060SC4.

**Comment by martinberlin** [comment]
Hello Florian the table does not really specify if it has the connector that is the issue.
It’s impossible to put all connectors in the same PCB. Before sending it to fabrication or buying a unit you have to always check what connector it has or design an adapter (there are some in that hardware repository)

**Comment by mickeprag** [comment]
Maybe we can make a separate table in the readme that lists the different connector on the boards?

**Comment by martinberlin** [comment]
Yes that’s a good idea. Because is confusing at least with this 39 pin connector since there are two (39 for 6”, 39 for 13.3”, different layout and pins)

**Comment by martinberlin** [comment]
@vroland maybe we could come up with some better idea to hold the "supported displays" table.
Or even to not show board version, just add a note in top: 

**Check the hardware repository before ordering display to make sure the PCB has the right connector.**

**Comment by martinberlin** [comment]
Also @floers we should state what compatible is:
**For this repository is that it can drive the display.**
A very different thema is if it has the connector. Because if it does not you can also check if there is an adapter for it. And if there is not, one can be designed, I did this myself for example to get a 6" working from the 40 pin FPC.

**Comment by vroland** [comment]
Indeed, we should make this more explicit in the readme :+1:

**Comment by martinberlin** [comment]
Closing here I will make a PR this weekend making more "explicit" what the readme states
Supported in vX means that the PCB supports the display but you need to make sure that has the right connector to handle it. Is impossible to cover in a single PCB all possible connectors for dozens of different displays
