### ISSUE TITLE
Q1 always open

### ISSUE THREAD

**Issue by x893** [vroland/epdiy#50]
Hi,
awesome project. 
i see that Q1 always open. Better add transistor to ground and SMPS_CTRL. Other pin of R1 connect to pin 2 of Q1.
I make a little bit changes in layout/components and all works fine.

Best wishes

**Comment by vroland** [comment]
Yes, I noticed that as well. This will be fixed in the next board revision, which will focus on a low deep sleep current (and add more connectors). I'll just leave this issue open until V5 is out, so others can find your workaround :)

**Comment by x893** [comment]
Yes, awesome idea but need redesign. Too many issues.
I'll wait next release.

Best wishes

**Comment by vroland** [comment]
Fixed in V5.
