### ISSUE TITLE
Unable to flash the board

### ISSUE THREAD

**Issue by amadeok** [vroland/epdiy#60]
Hello,
I'm having issues flashing projects to the board. Sometimes i can, then after a while i can no longer flash, i get error: "A fatal error occurred: Timed out waiting for packet content"
Would you happen to know any solution? I was thinking about replacing the HL-340 
thanks

**Comment by vroland** [comment]
Which board revision are you using? Maybe try a different cable or reduce upload speed?

**Comment by amadeok** [comment]
> Which board revision are you using? Maybe try a different cable or reduce upload speed?

Hi thanks for reply. I have revision 4, i did try another cable and a lower upload speed. I was thinking about soldering some wires to the controller board and using a standard esp32 development board( such as : https://images-na.ssl-images-amazon.com/images/I/61wqT2HjXxL._AC_SL1000_.jpg) to power the controller board and control the signals, could this work?

**Comment by vroland** [comment]
You could just solder to the RX / TX lines to a normal usb to UART converter, like a esp8266 programmer.
Bodging such a complete module seems more difficult.

**Comment by vroland** [comment]
@amadeok Do you still have problems here or can this issue be closed?

**Comment by amadeok** [comment]
Hi, yes you can close it, it seems that that board got damage somehow

Il giorno dom 28 feb 2021 alle ore 11:21 Valentin Roland <
notifications@github.com> ha scritto:
