### ISSUE TITLE
LT1945 issues

### ISSUE THREAD

**Issue by M737M737** [vroland/epdiy#73]
Hi,
I soldered a v4 board and tested it without the ePaper display connected. Unfortunately, part U2 (LT1945) burnt down between the pins 6 & 7 (top left). As I'm not that experienced at SMD soldering, I gave it a new try, soldered a new board and tested every single connection, it was all fine. However, the part burnt down at exactly the same place.

All parts were ordered from LCSC, LT1945 from AliExpress (https://www.aliexpress.com/item/32863876207.html?spm=a2g0s.9042311.0.0.290d4c4dfx2shh)

Has someone else faced this issue?
Is testing without the ePaper display recommended?

At the 2nd try I didn't solder the esp32 for now. Could this be the problem?

Thanks!

**Comment by vroland** [comment]
Hi,
sorry to hear that. Maybe check that the orientation on all the parts is correct? The silkscreen markings seem to be unfamiliar to some people: The elongated line correspons to where the dot on the package should be. So maybe something is wrong there?
Also, which diodes are you using? At the beginning of the project, I had a chip burn out because I used normal diodes instead of schottky diodes.
Lastly, counterfeit chips on AliExpress are not unheard of. If you ruled out the other reasons, could you upload a picture of the package markings? 
Hope you find it!

Regards,

Valentin

**Comment by M737M737** [comment]
Hi,
I just double checked the orientation and it should be fine. (see attached photos for reference)
![LT1945_pcb](https://user-images.githubusercontent.com/76554798/113609088-9e734480-964b-11eb-950d-44f6cab0269e.jpeg)
![LT1945_datasheet](https://user-images.githubusercontent.com/76554798/113609109-a29f6200-964b-11eb-87b5-2820f3340434.jpg)
![LT1945_breakout](https://user-images.githubusercontent.com/76554798/113609115-a4692580-964b-11eb-8eb7-a4fd697ce17c.jpg)

Schottky diodes should be also ok: https://lcsc.com/product-detail/Schottky-Barrier-Diodes-SBD_ON-Semiconductor-MBR0540T1G_C21353.html
For orientation, I reffered to the kicad v4 breakout plan.
![schottky_orientation](https://user-images.githubusercontent.com/76554798/113609127-a92dd980-964b-11eb-9b9b-57c10faadf7f.jpg)


I also attached a picture of the package. I got 10 pc., no further markings or information.
The only interesting thing is the additional "e3" marking on some pieces.
![LT1945_package](https://user-images.githubusercontent.com/76554798/113609144-ad59f700-964b-11eb-92ba-0a3834ace0c6.jpg)

Any ideas?

Thank you very much!

**Comment by vroland** [comment]
Hm, I don't see anything wrong either. I'll compare your photos with my boards when I get home after easter at the end of the week. Unfortunately I can't really do anything more from here :/

**Comment by M737M737** [comment]
Alright, thank you!

**Comment by vroland** [comment]
Hm, of mine, none have the additional e3... Everything else seems to match though :/

**Comment by M737M737** [comment]
Ok, can you send me a link of your LT1945's?

**Comment by vroland** [comment]
This is the link I've used: https://www.aliexpress.com/item/2053692331.html?spm=a2g0s.9042311.0.0.27424c4dbMlSvC although the listing seems to have been replaced since then, because it only says 2 orders.

**Comment by mcer12** [comment]
@M737M737  There's some other issue, probably a short somewhere, maybe a diode soldered in reverse. Check everything connected to that LT1945. It's 99% not problem with the regulators. I have both types, ones with "e3" in the corner and ones without it and they all work fine.

**Comment by M737M737** [comment]
Ok, thank you! I'll check that again.

**Comment by markbirss** [comment]
> Hi,
> I just double checked the orientation and it should be fine. (see attached photos for reference)
> ![LT1945_pcb](https://user-images.githubusercontent.com/76554798/113609088-9e734480-964b-11eb-950d-44f6cab0269e.jpeg)
> ![LT1945_datasheet](https://user-images.githubusercontent.com/76554798/113609109-a29f6200-964b-11eb-87b5-2820f3340434.jpg)
> ![LT1945_breakout](https://user-images.githubusercontent.com/76554798/113609115-a4692580-964b-11eb-8eb7-a4fd697ce17c.jpg)
> 
> Schottky diodes should be also ok: https://lcsc.com/product-detail/Schottky-Barrier-Diodes-SBD_ON-Semiconductor-MBR0540T1G_C21353.html
> For orientation, I reffered to the kicad v4 breakout plan.
> ![schottky_orientation](https://user-images.githubusercontent.com/76554798/113609127-a92dd980-964b-11eb-9b9b-57c10faadf7f.jpg)
> 
> I also attached a picture of the package. I got 10 pc., no further markings or information.
> The only interesting thing is the additional "e3" marking on some pieces.
> ![LT1945_package](https://user-images.githubusercontent.com/76554798/113609144-ad59f700-964b-11eb-92ba-0a3834ace0c6.jpg)
> 
> Any ideas?
> 
> Thank you very much!

My 5 x boards was made by PCBWay and I have those LT1945's with the e markings as the other was out of stock

![T-1Y2W298575A picture for assembly (2)](https://user-images.githubusercontent.com/22388007/116812399-dc7e5e00-ab4e-11eb-8492-a8a87d2bf774.jpg)

**Comment by mcer12** [comment]
To sum this up, use flux, check for solder bridges and buy from good sources. Closing.
