### ISSUE TITLE
will rotation be added to main branch

### ISSUE THREAD

**Issue by rolohaun** [vroland/epdiy#74]
Is rotation going to be added to the main branch or should I just use the epdiy-rotation fork?

**Comment by vroland** [comment]
Yes, the rotation will be merged soon, some small things still need to be fixed. You can either wait or just use the rotation fork until the merge and then port to the main branch ;)

**Comment by rolohaun** [comment]
thank you for the info! Excellent work on the driver, the displays you support are far nicer and cheaper than what waveshare sells!

**Comment by martinberlin** [comment]
@rolohaun if you test the fork and discover something please report on #71 
The more people it test the better so correct things before the merge.
