### ISSUE TITLE
How to calibrate RV1?

### ISSUE THREAD

**Issue by sebastius** [vroland/epdiy#8]
Messed with RV1 and now i've got a completely black screen :laughing: , any hints on calibrating RV1 and also recover the eink to normal?

No this is worse. I blew up the opamp... Replaced it and it now works again. Rotating RV1 too close somewhere apparantly blew op U7. 

Regarding the opamp i've submitted a PR to properly close the second opamp, it could be related but not sure.

**Comment by vroland** [comment]
Hmm, aside from the sencond opamp, I'm not sure why the opamp would blow...
But yes, I calibrated by holding a multimeter to the opamp pin ;) 
I could add a test pad for VCOM (and a calibration program which just activates the power supply).  Or do you have a better Idea?

**Comment by sebastius** [comment]
The main question is: What should i calibrate it to?

**Comment by vroland** [comment]
There is usually a sticker with a negative number (usually -1 to -3, e.g. -1.27) somewhere on the ribbon cable. This is the voltage you should calibrate to ;)

**Comment by sebastius** [comment]
> I could add a test pad for VCOM (and a calibration program which just activates the power supply). Or do you have a better Idea?
I can get a nice calibration pad in probably (i need to re-add the mounting holes anyway), if you can make a tiny calibration program, it would be great!

**Comment by sebastius** [comment]
Calibrated mine, made the calibration program myself, turned out to be easier than expected. Will write a request with code + documentation tomorrow :)
