### ISSUE TITLE
Image not getting displayed properly

### ISSUE THREAD

**Issue by Schmirgus** [vroland/epdiy#89]
Hello :)
two weeks ago i finally found a vendor who allegedly sold me an "ED097OC4". Unfortunately there arent any stickers for the VCOM or the display type. When i tried the demo and other examples, it seems that theres something wrong.

https://www.youtube.com/watch?v=NaMCH7J34ug

 I tried different VCOM voltages in a range of -1 to -3V with no differents. Also i tried the ED970TC2, ED970OC4 and ED970OC4 low quality in the config with no difference. When i unpacked the display the contrast etc seemed fine.
![Unbenannt](https://user-images.githubusercontent.com/58094389/121170181-23015f80-c855-11eb-9d1b-afdc1b96af7b.png)
Has anyone seeing a similiar issue ?

thanks :)

**Comment by Schmirgus** [comment]
i incread the VCOM to -4V and the pictures is getting better  :/ any ideas?

**Comment by vroland** [comment]
Hm, this does indeed look like a VCOM or display type issue. But I've not yet seen displays with VCOM voltages in excess of -3V.
Does this effect change if you select different display types like SC4 or 047TC2?

**Comment by Schmirgus** [comment]
I guess the quality of the display isnt that great. There must be a reason why there isnt a frame around the glas and the sticker is missing. Maybe this display got sorted out? I wonder tho why the original picture that was displayed on the screen looked fine.

Nevertheless increasing the VCOM -5V gave me the best quality but then the whites are obviously pretty bad. The ED06SC4 and the 047TC1 settings definitely resulted in a better picture quality.

**Comment by vroland** [comment]
Sorry for the late reply. With these displays its always hard to know if they have some previous fault or are just slightly different models. Btw, did you measure that all the voltages are correct on your board? Maybe there is something wrong with them. Maybe test your board with another display?

**Comment by Schmirgus** [comment]
Hey ;) sorry for the late reply, i was finishing my thesis. Unfortunately i dont got a second display :/. Unfortunately i dont got an oscilloscope to check all the voltages properly.

**Comment by vroland** [comment]
Hm, maybe. Can you upload an image of your board? Maybe some control pins are bridged on the connector? But I'm running out of ideas, so I tend to blame the display :D

**Comment by mcer12** [comment]
Closing, stale. @Schmirgus feel free to reopen once you have the required test equipment.
