### ISSUE TITLE
U4 vreg unnecessary?

### ISSUE THREAD

**Issue by sebastius** [vroland/epdiy#98]
![image](https://user-images.githubusercontent.com/14947839/128614360-99e55fcc-2296-4c2e-9d7d-1e52e886e741.png)

If you hook up pin 16 of U12 (CH340C) to VBUS, and pin 4 to a 100nF cap (C16)  (and GND), then you can drop U4 and C13/C14. Saves you a few cents and 1cm^2 of board space :)

I'm currently building a board but i don't have all the parts to verify. Can confirm that the USB-serial is working with my mod.

**Comment by vroland** [comment]
Since the CH340C would be in 5V mode, wouldn't the output signals 5V as well? Afaik, although the esp32 seems to be practially 5V tolerant (at least for some time), technically it could burn out the input pins. So I'd rather be on the safe side :)

**Comment by mcer12** [comment]
@sebastius  ESP32 is NOT 5V tolerant as opposed to ESP8266. If you look up schematics of the development boards, they all use 3V3 to power the CH340.

**Comment by vroland** [comment]
I think this question was answered. If not, feel free to re-open @sebastius :)
